### ISSUE TITLE
Can not be installed on Eclipse for PHP Developrs Oxygen.1a Release 4.7.1a

### ISSUE THREAD

**Issue by levshinovsky** [kKEo/yiiclipse#11]
Yiiclipse (http://yiiclipse.maziarz.org/updatesite/1.2) can not be installed on Eclipse for PHP Developrs Oxygen.1a Release 4.7.1a with message: 

Cannot complete the install because one or more required items could not be found.
  Software being installed: Yiiclipse Core 1.2.0.201301050012 (org.maziarz.yiiclipse.feature.feature.group 1.2.0.201301050012)
  Missing requirement: Yiiclipse 1.2.0.201301050012 (org.maziarz.yiiclipse 1.2.0.201301050012) requires 'package org.eclipse.php.internal.core.compiler.ast.nodes 0.0.0' but it could not be found

**Comment by bchai123** [comment]
Do we have a solution here?

**Comment by pedromalta** [comment]
Anyone?

**Comment by wserious** [comment]
Same problem, and don't know how to solve. So my yii project always report uncorrect error like "import cannot be resolved". But website can go well.

**Comment by zahadom** [comment]
Has anyone found a solution?
What is the version of Eclipse with which it works?

**Comment by kKEo** [comment]
I've just updated `Yiiclipse` for being compatible with the most recent `Eclipse PHP Development Tools` which is called `Photon` and is the succesor of `Oxygen` release. It was even not that hard as I expected after 5 year gap since last upgrade ;). Hope everything works well - if not, please add an isssue with detailed description. New update site is: `http://yiiclipse.maziarz.org/updatesite/1.18`.
PS. `Oxygen` should also work, if not, just upgrade PDT to `Photon` ;>

**Comment by SSiwek** [comment]
Hi!

Can't install. The UpdateSite gives only Core 1.18.7  


Cannot complete the install because one or more required items could not be found.
  Software being installed: Yiiclipse Core 1.18.7.201807141519 (org.maziarz.yiiclipse.feature.feature.group 1.18.7.201807141519)
  Missing requirement: org.maziarz.yiiclipse 1.18.7.201807141519 (org.maziarz.yiiclipse 1.18.7.201807141519) requires 'bundle org.eclipse.php.core.parser 6.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Yiiclipse Core 1.18.7.201807141519 (org.maziarz.yiiclipse.feature.feature.group 1.18.7.201807141519)
    To: org.maziarz.yiiclipse [1.18.7.201807141519]

**Comment by kKEo** [comment]
Seems `org.eclipse.php.core.parser` was upgraded to 6.0.0 in `Photon` release. If you can, please download the newest PDT and try again.

**Comment by SSiwek** [comment]
Hi,
I am using Oxygene. And there aren't any updates via http://download.eclipse.org/tools/pdt/updates/oxygen
available.

It seems for Oxygene there is only 5.3.0.302803070838

What can I do now?
